"""empty message

Revision ID: efa8637d411d
Revises: 6367735f2f16
Create Date: 2018-05-08 20:23:21.781908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa8637d411d'
down_revision = '6367735f2f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'age')
    # ### end Alembic commands ###
